export const ACTION_NAME_UPLOAD_FLOOR_PLAN = 'ACTION_NAME_UPLOAD_FLOOR_PLAN';
export const ACTION_NAME_UPLOAD_DESIGN = 'ACTION_NAME_UPLOAD_DESIGN';
export const ACTION_NAME_CLEAN_OBJECT_URLS = 'ACTION_NAME_CLEAN_OBJECT_URLS';
export const ACTION_NAME_SUBMIT_WIZARD_DATA = 'ACTION_NAME_SUBMIT_WIZARD_DATA';
export const ACTION_NAME_FETCH_USER_DATA = 'ACTION_NAME_FETCH_USER_DATA';

export const VALID_TYPES = ['image/png', 'image/jpg', 'image/jpeg', 'image/webp'];
